#!/usr/bin/env python

# get DID info from voip.ms API

#   get-did-info.py --help     - print options
#   get-did-info.py            - print list of DID numbers
#   get-did-info.py --account  - print list (sub)account:DID-number
#   get-did-info.py --all      - print all data available about the DID(s)

# Copyright 2018 RJ White
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# ---------------------------------------------------------------------

# need 3rd party Config from github.com/rjwhite/Python-config-module
# add the default path if they installed it as a normal user via
#    python setup.py install --user=~

import os
import sys
import json

version       = 'v0.3'
progname      = sys.argv[0]
config_file   = ".voip-ms.conf"
debug_flag    = False

home = os.environ[ 'HOME' ]
if home:
    pathname = home + '/' + ".voip-ms.conf"
    if os.path.isfile( pathname ):
        config_file = pathname


# need config module from Github
config_module = "https://github.com/rjwhite/Python-config-module"
sys.path.append( home + '/lib/python' )
try:
    import config
except ImportError as err:
    sys.stderr.write( "{0}: Please install config module\n". \
        format( progname ))
    sys.stderr.write( "{0}: can be obtained from {1}\n". \
        format( progname, config_module ))
    sys.exit(1)

# may need to get requests module, via pip
try:
    import requests
except ImportError as err:
    sys.stderr.write( "{0}: {1}\n".format( progname, err ))
    sys.stderr.write( "{0}: You may need to do a \'pip install requests\'\n". \
        format( progname ))
    sys.exit(1)


class BadWebCall( Exception ): pass



# debug function if --debug|-d option given
#
# Arguments:
#   string to print
# Returns:
#   0
# Exceptions:
#   none
# Globals:
#   debug_flag

def dprint( msg ):
    global debug_flag

    if debug_flag == False: return(0)
    print( msg )
    return(0) ;


# send a URL to the Voip.ms API
#
# Arguments:
#   1:  URL
# Returns:
#   JSON structure
# Exceptions:
#   BadWebCall

def send_request( url ):
    my_name = sys._getframe().f_code.co_name

    dprint( "{0}(): URL = {1}".format( my_name, url ))

    try:
        res = requests.get( url )
        json_data = res.text
        json_struct = json.loads( json_data )
        status = str( json_struct[ 'status' ] )
    except Exception as err:
        raise BadWebCall( "{0}(): {1}".format( my_name, err ))

    if status != 'success':
        raise BadWebCall( "{0}(): Failed status: {1}". \
            format( my_name, status ))

    dprint( "{0}(): status = {1}".format( my_name, status ))

    return( json_struct )


# print usage
#
# Arguments:
#   none
# Returns:
#   0
# Exceptions:
#   none
# Global variables:
#   config_file

def usage():
    print( "usage: {} [options]*".format( sys.argv[0] ))

    options = """\
    [-a|--all]             (all info about DID(s))
    [-c|--config file]     (config-file. (default={})
    [-d|--debug]           (debugging output)
    [-h|--help]            (help)
    [-l|--line phone-num]  (DID-number)
    [-A|--account]         (print (sub)account name(s) instead of DID)
    [-V|--version]         (print version of this program)\
    """

    print( options.format( config_file ))
    return(0)


# main program
#
# Arguments:
#   none
# Returns:
#   0:  ok
#   1:  not ok
# Exceptions:
#   none
# Global variables:
#   config_file, debug_flag

def main():
    global config_file, debug_flag

    all_info_flag = False
    account_flag  = False
    method        = 'getDIDsInfo'
    did           = None

    num_args = len( sys.argv )
    i = 1
    while i < num_args:
        try:
            arg = sys.argv[i]
            if arg == '-c' or arg == '--config':
                i = i + 1 ;     config_file = sys.argv[i]
            elif arg == '-l' or arg == '--line':
                i = i + 1 ;     did = sys.argv[i]
            elif arg == '-A' or arg == '--account':
                account_flag = True
            elif arg == '-d' or arg == '--debug':
                debug_flag = True
            elif arg == '-a' or arg == '--all':
                all_info_flag = True
            elif arg == '-h' or arg == '--help':
                usage()
                return(0)
            elif arg == '-V' or arg == '--version':
                print( "version: {0}".format( version ))
                return(0)
            else:
                sys.stderr.write( "{0}: unknown option: {1}\n". \
                    format( progname, arg ))
                return(1)

        except IndexError as err:
            sys.stderr.write( "{}: {}.  Missing argument value to \'{}\'?\n". \
                format( progname, err, arg ))
            return(1)

        i = i+1


    config.Config.set_debug( debug_flag )

    # no definitions file.  Our type info is all in our config file.
    try:
        conf = config.Config( config_file, '', AcceptUndefinedKeywords=True )
    except Exception as err:
        sys.stderr.write( "{0}: {1}\n".format( progname, err ))
        return(1)

    dprint( "Config data read ok.  woohoo." )


    # make sure we have our mandatory sections
    num_errors = 0
    needed_sections = [ 'authentication' ]
    sections = conf.get_sections()
    for section in needed_sections:
        if section not in sections:
            num_errors = num_errors + 1
            sys.stderr.write( "{0}: missing section \'{1}\' in {2}\n". \
                format( progname, section, config_file ))

    if num_errors > 0:
        return(1)

    # make sure we have our mandatory keywords for authentication
    keywords_i_need = [ 'user', 'pass' ]
    keywords = conf.get_keywords( 'authentication' )
    for keyword in keywords_i_need:
        if keyword not in keywords:
            err = "missing keyword \'{0}\'".format( keyword )
            err = err + " in section \'authentication\' in {0}". \
                format( config_file )
            sys.stderr.write( "{0}: {1}\n".format( progname, err ))
            num_errors += 1

    if num_errors > 0:
        return(1)

    userid   = conf.get_values( 'authentication', 'user' )
    password = conf.get_values( 'authentication', 'pass' )

    dprint( "user\t= {0}".format( userid ))
    dprint( "pass\t= {0}".format( password ))

    # see if DID is given, and if so, format it correctly

    if did:
        dprint( "DID number was given as a command-line option: {0}". \
            format( did ))
        did = did.replace( '-', '' )        # remove dashes
        did = did.replace( ' ', '' )        # remove spaces

        if did.isdigit() == False:
            sys.stderr.write( "{0}: DID is not numeric: {1}\n". \
                format( progname, str(did)))
            return(1)

        dprint( "Command-line option DID number is now: {0}".format( did ))

    if did:
        dprint( "Final DID number being used is {0}".format( did ))

    # build the URL 
    url = "https://voip.ms/api/v1/rest.php" + \
            "?api_username={0}&api_password={1}&method={2}". \
                format( userid, password, method )

    if did:
        url = url + "&did={0}".format( did )

    dprint( "URL = " + url )

    try:
        json_struct = send_request( url )
    except BadWebCall as err:
        sys.stderr.write( "{0}: {1}\n".format( progname, str(err)))
        return(1)

    # get number of DIDs returned

    num_dids = len( json_struct[ 'dids' ] )
    dprint( "Number of DIDs found is " + str( num_dids ))

    # we want to figure out the maximum length of the keywords.
    # and we only want to do it once, so only the first DID is used

    did_keys = list( json_struct[ 'dids' ][ 0 ] )
    max_key_len = len( max( did_keys, key=len ))

    # now get our data

    if 'dids' not in json_struct:
        sys.stderr.write( "{0}: missing key \'did\' in return data\n". \
            format( progname ))
        return(1)

    i = 0
    for d in json_struct[ 'dids' ]:
        try:
            line = json_struct[ 'dids' ][ i ][ 'did' ]
        except ( KeyError ) as err:
            dprint( "Could not get DID (line) name: {0}. skipping.". \
                format( err ))
            continue

        try:
            account = json_struct[ 'dids' ][ i ][ 'routing' ]
        except ( KeyError ) as err:
            dprint( "Could not get routing (account) name: {0}".format( err ))
            dprint( "Setting account to \'unknown\'" ) 
            account = 'unknown'

        if account_flag == True:
            account = account.replace( 'account:', '' )
            did_info = account + ':' + line
        else:
            did_info = line

        print( did_info )

        # now print the rest of the data
        if all_info_flag:
            for did_field in did_keys:
                try:
                    v = str( json_struct[ 'dids' ][ i ][ did_field ] )
                except ( KeyError ) as err:
                    dprint( "Could not get value for DID {0}". \
                        format( did_field))
                    dprint( "Setting DID to empty string" )
                    v = ""

                format_str = "\t{0:" + str( max_key_len ) + "s}    {1}"
                print( format_str.format( did_field, v ))

            if num_dids > 1: print( "" )

        i = i + 1

    return(0)


# let er rip...

if main():
    sys.exit(1)
else:
    sys.exit(0)
